Email-Id: mhammad42210@gmail.com\
Kaggle-Id: https://www.kaggle.com/hammadali9988779988\
Github-Id: https://github.com/hammadali99418\
Linkedin-Id1: https://www.linkedin.com/in/hammad-ali-ba3040345

# Matrix or Matrices

### Import library

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3],[4, 5, 6]])
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Create a martrix of big dimensions
b = np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

## slice the matrix

In [ ]:
b = np.arange(0,100,2).reshape(5,10)
b[1:3, 3:5] # first two rows and first three columns

array([[26, 28],
       [46, 48]])

In [23]:
# silicing of a matrix 3x2 # 3 rows and 2 columns
c = b[0:3,4:6]
c

array([[ 8, 10],
       [28, 30],
       [48, 50]])

In [28]:
b.max() # maximum value of the matrix




np.int64(98)

In [29]:
b.min() # minimum value of the matrix

np.int64(0)

In [30]:
b.sum() # sum of all values in the matrix

np.int64(2450)

In [31]:
b.min(axis=0) # minimum value of each column

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
b.min(axis=1) # minimum value of each row

array([ 0, 20, 40, 60, 80])

In [33]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [34]:
b.max(axis=0) # maximum value of each column

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [38]:
b.max(axis=1) # minimum value of each row

array([18, 38, 58, 78, 98])

In [39]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [41]:
add = m + 1 # add 1 to each element of the matrix
add

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [42]:
m + np.array([5,10]) # add 1 to each element of the matrix

array([[ 5, 12],
       [ 9, 16],
       [13, 20],
       [17, 24],
       [21, 28]])

In [43]:
np.vstack((m, np.array([25,30]))) # add a new row to the matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [25, 30]])

In [44]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

## Reverse an array

In [45]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])